export const siteName = 'সামান্তরিক ব্লগ'
export const siteSlogun = 'বাংলা ভাষায় হৃদয়ের স্পন্দন'
export const imageUrl = 'https://www.shamantorik.com/main_logo.jpg'
export const siteUrl = 'https://www.shamantorik.com'
export const siteDesc = 'বাংলাদেশ এর বৃহত্তম বাংলা ব্লগিং ওয়েব পোর্টাল। বাংলা ভাষায় সাহিত্য চর্চা, গল্প, কবিতা, উপন্যাস, ধারাবাহিক গল্প লেখা ও মত প্রকাশের জন্য সামান্তরিক ব্লগ একটি সময়পযোগি মাধ্যম। ব্লগটি ১০ই নভেম্বর ২০২২ এ মোস্তাফিজুর রহমান এর হাত ধরে প্রতিষ্ঠিত হয়েছে'
